import "dotenv/config";
import { getPrisma } from "../src/prisma.js";

// Prints the API and database evidence used in the Lab 2 submission PDF
// (Parts 6 and 8): the Ticket Number and requesterId really come from the
// backend and the database, and ownership/soft-removal rules are enforced
// by the API and not only hidden in the UI.
//
// Run with the API on http://localhost:3000:  npm run evidence

const API = process.env.EVIDENCE_API_URL ?? "http://localhost:3000";

function line(title: string) {
  console.log(`\n----- ${title} -----`);
}

async function call(path: string, init: RequestInit = {}, requesterId?: number) {
  const headers = new Headers(init.headers);
  if (requesterId !== undefined) headers.set("X-Dev-Requester-Id", String(requesterId));
  if (init.body && !(init.body instanceof FormData)) headers.set("Content-Type", "application/json");
  const res = await fetch(`${API}${path}`, { ...init, headers });
  const type = res.headers.get("content-type") ?? "";
  const body = type.includes("application/json") ? await res.json() : await res.text();
  return { status: res.status, body, headers: res.headers };
}

async function main() {
  const prisma = getPrisma();

  const [requesterA, requesterB] = await prisma.requesterUser.findMany({
    where: { isActive: true },
    orderBy: { id: "asc" },
    take: 2,
  });
  if (!requesterA || !requesterB) throw new Error("Seed the database first: npm run prisma:seed");

  const category = await prisma.category.findFirstOrThrow({ where: { isActive: true } });
  const relatedSystem = await prisma.relatedSystem.findFirstOrThrow({ where: { isActive: true } });

  console.log(`Requester A = ${requesterA.name} (id ${requesterA.id})`);
  console.log(`Requester B = ${requesterB.name} (id ${requesterB.id})`);

  line("1. POST /api/tickets as Requester A (Ticket Number generated by the backend)");
  const created = await call(
    "/api/tickets",
    {
      method: "POST",
      body: JSON.stringify({
        categoryId: category.id,
        relatedSystemId: relatedSystem.id,
        summary: "Evidence run: cannot connect to the VPN",
        description: "Created by the evidence script to show the saved values come from the database.",
        requestedPriority: "HIGH",
      }),
    },
    requesterA.id
  );
  console.log(`HTTP ${created.status}`);
  console.log(JSON.stringify(created.body, null, 2));

  const ticketId = (created.body as { id: number }).id;

  line("2. Same Ticket read straight from PostgreSQL (Prisma), not from the API");
  const row = await prisma.ticket.findUniqueOrThrow({
    where: { id: ticketId },
    select: {
      id: true,
      ticketNumber: true,
      requesterId: true,
      summary: true,
      requestedPriority: true,
      currentStatus: true,
      createdAt: true,
    },
  });
  console.log(JSON.stringify(row, null, 2));
  console.log(
    `requesterId in the database (${row.requesterId}) matches the selected Development Requester (${requesterA.id}): ${
      row.requesterId === requesterA.id
    }`
  );

  line("3. GET /api/tickets/:id as Requester B (owner is Requester A)");
  const foreign = await call(`/api/tickets/${ticketId}`, {}, requesterB.id);
  console.log(`HTTP ${foreign.status} ${JSON.stringify(foreign.body)}`);

  line("4. Upload an attachment as Requester A");
  const png = Buffer.from(
    "89504e470d0a1a0a0000000d4948445200000001000000010802000000907753de0000000c4944415478" +
      "9c63f8cfc00000030101001830900000000049454e44ae426082",
    "hex"
  );
  const form = new FormData();
  form.append("file", new Blob([new Uint8Array(png)], { type: "image/png" }), "evidence.png");
  const uploaded = await call(
    `/api/tickets/${ticketId}/attachments`,
    { method: "POST", body: form },
    requesterA.id
  );
  console.log(`HTTP ${uploaded.status}`);
  console.log(JSON.stringify(uploaded.body, null, 2));
  const attachmentId = (uploaded.body as { id: number }).id;

  line("5. Download the active attachment as Requester A");
  const download = await fetch(`${API}/api/attachments/${attachmentId}/download`, {
    headers: { "X-Dev-Requester-Id": String(requesterA.id) },
  });
  console.log(
    `HTTP ${download.status}, Content-Type ${download.headers.get("content-type")}, Content-Disposition ${download.headers.get(
      "content-disposition"
    )}`
  );

  line("6. Download the same attachment as Requester B");
  const foreignDownload = await call(`/api/attachments/${attachmentId}/download`, {}, requesterB.id);
  console.log(`HTTP ${foreignDownload.status} ${JSON.stringify(foreignDownload.body)}`);

  line("7. Soft-remove the attachment as Requester A (reason required)");
  const noReason = await call(
    `/api/attachments/${attachmentId}`,
    { method: "DELETE", body: JSON.stringify({}) },
    requesterA.id
  );
  console.log(`Without a reason: HTTP ${noReason.status} ${JSON.stringify(noReason.body)}`);

  const removed = await call(
    `/api/attachments/${attachmentId}`,
    { method: "DELETE", body: JSON.stringify({ reason: "Evidence run: wrong file uploaded" }) },
    requesterA.id
  );
  console.log(`With a reason: HTTP ${removed.status} ${JSON.stringify(removed.body)}`);

  line("8. Download the removed attachment again (soft removal blocks the file)");
  const goneDownload = await call(`/api/attachments/${attachmentId}/download`, {}, requesterA.id);
  console.log(`HTTP ${goneDownload.status} ${JSON.stringify(goneDownload.body)}`);

  line("9. Removed attachment metadata is still stored in the database");
  const attachmentRow = await prisma.attachment.findUniqueOrThrow({
    where: { id: attachmentId },
    select: {
      id: true,
      originalName: true,
      mimeType: true,
      sizeBytes: true,
      uploadedAt: true,
      removedAt: true,
      removedReason: true,
      removedById: true,
    },
  });
  console.log(JSON.stringify(attachmentRow, null, 2));

  line("10. Inactive Requester is never returned by the selector endpoint");
  const inactive = await prisma.requesterUser.findFirst({ where: { isActive: false } });
  const selector = await call("/api/requesters");
  const ids = (selector.body as { id: number }[]).map((r) => r.id);
  console.log(`Inactive requester in the database: ${inactive?.name} (id ${inactive?.id})`);
  console.log(`GET /api/requesters returns ids: ${ids.join(", ")}`);
  console.log(`Inactive id present in the response: ${inactive ? ids.includes(inactive.id) : "n/a"}`);

  await prisma.$disconnect();
}

main().catch(async (err) => {
  console.error(err);
  await getPrisma().$disconnect();
  process.exit(1);
});
